--------------------------------------------------------
--  File created - Thursday-February-08-2018   
--------------------------------------------------------
-- Unable to render TABLE DDL for object STUDY.SAL with DBMS_METADATA attempting internal generator.
CREATE UNIQUE INDEX STUDY.SAL_PK_SNUM ON STUDY.SAL (SNUM ASC) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE STUDY.SAL 
(
  SNUM NUMBER(4, 0) NOT NULL 
, SNAME VARCHAR2(10 BYTE) NOT NULL 
, CITY VARCHAR2(10 BYTE) NOT NULL 
, COMM NUMBER(7, 2) NOT NULL 
, CONSTRAINT SAL_PK_SNUM PRIMARY KEY 
  (
    SNUM 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE SYSTEM 
PCTFREE 10 
PCTUSED 40 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  FREELISTS 1 
  FREELIST GROUPS 1 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS
REM INSERTING into STUDY.SAL
SET DEFINE OFF;
Insert into STUDY.SAL (SNUM,SNAME,CITY,COMM) values (1001,'Peel','London',0.12);
Insert into STUDY.SAL (SNUM,SNAME,CITY,COMM) values (1002,'Serres','San Jose',0.13);
Insert into STUDY.SAL (SNUM,SNAME,CITY,COMM) values (1004,'Motica','London',0.11);
Insert into STUDY.SAL (SNUM,SNAME,CITY,COMM) values (1007,'Rifkin','Barcelona',0.15);
Insert into STUDY.SAL (SNUM,SNAME,CITY,COMM) values (1003,'Axelrod','New York',0.1);
